export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        {/* Header */}
        <header className="bg-blue-600 text-white p-4 text-center shadow-md">
          <h1 className="text-xl font-bold">My Next.js App</h1>
        </header>

        {/* Main Content */}
        <main className="flex-grow p-4">{children}</main>

        {/* Footer */}
        <footer className="bg-gray-800 text-white p-4 text-center mt-auto">
          <p>&copy; {new Date().getFullYear()} My Next.js App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}